version: '3.8'

services:
  #============================================================================
  # Neon Local - PostgreSQL proxy for development
  #============================================================================
  neon-local:
    image: postgres:15-alpine
    container_name: acquisitions-neon-local
    platform: linux/amd64
    ports:
      - '5432:5432'
    env_file:
      - .env.development
    volumes:
      # Persist data across container restarts
      - neon_local_data:/var/lib/postgresql/data
      # Optional: Custom initialization scripts
      - ./docker/init-scripts:/docker-entrypoint-initdb.d:ro
    networks:
      - acquisitions-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U neondb_owner -d neondb']
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  #============================================================================
  # Application - Development mode with hot reload
  #============================================================================
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: acquisitions-app-dev
    ports:
      - '3000:3000'
    env_file:
      - .env.development
    volumes:
      # Mount source code for hot reload
      - ./src:/app/src:ro
      - ./package.json:/app/package.json:ro
      - ./package-lock.json:/app/package-lock.json:ro
      # Mount logs directory for persistence
      - ./logs:/app/logs
      # Exclude node_modules to prevent conflicts
      - /app/node_modules
    networks:
      - acquisitions-network
    depends_on:
      neon-local:
        condition: service_healthy
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:3000/health || exit 1']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

  #============================================================================
  # Optional: Database GUI (Adminer) for development
  #============================================================================
  adminer:
    image: adminer:4.8.1-standalone
    container_name: acquisitions-adminer
    ports:
      - '8080:8080'
    environment:
      ADMINER_DEFAULT_SERVER: neon-local
      ADMINER_DESIGN: pepa-linha-dark
    networks:
      - acquisitions-network
    depends_on:
      - neon-local
    profiles:
      - tools
    restart: unless-stopped

#==============================================================================
# Networks
#==============================================================================
networks:
  acquisitions-network:
    driver: bridge
    name: acquisitions-network

#==============================================================================
# Volumes
#==============================================================================
volumes:
  neon_local_data:
    name: acquisitions-neon-local-data
